import React, { FC, HTMLAttributes } from 'react'

interface IProps extends HTMLAttributes<HTMLDivElement> {

}

const Spinner: FC<IProps> = ({className}) => {
    return (
        <div className='h-screen w-screen absolute z-30 bg-black opacity-70 top-0 left-0 flex justify-center items-center'>
            <svg xmlns="http://www.w3.org/2000/svg" width="40px" height="40px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
                <circle cx="50" cy="50" fill="none" stroke="white" stroke-width="8" r="40" stroke-dasharray="131.94689145077132 45.982297150257104">
                    <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="0.941176470588235s" values="0 50 50;360 50 50" keyTimes="0;1"></animateTransform>
                </circle>
                {/* [ldio] generated by https://loading.io/ */}
            </svg>
        </div>
    )
}

export default Spinner